# Apply Numpy 20 Universal functions 

In [1]:
import numpy as np

In [2]:
a = np.array([-2, -1, 0, 1, 2])

In [3]:
# 01 - Absolute value
print(np.abs(a))  # [2 1 0 1 2]

[2 1 0 1 2]


In [4]:
# 02 - Addition
b = np.array([3, 4, 5, 6, 7])
print(np.add(a, b))  # [1 3 5 7 9]

[1 3 5 7 9]


In [5]:
# 03 - Subtraction
print(np.subtract(b, a))  # [5 5 5 5 5]


[5 5 5 5 5]


In [6]:
# 04 - Multiplication
print(np.multiply(a, b))  # [-6 -4 0 6 14]

[-6 -4  0  6 14]


In [7]:
# 05 - Division
print(np.divide(b, a))  # [-1.5 -4. inf 6. inf]


[-1.5 -4.   inf  6.   3.5]


C:\Users\HP ZBOOK 17\AppData\Local\Temp\ipykernel_11804\3583872946.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(b, a))  # [-1.5 -4. inf 6. inf]


In [8]:
# 06 - Exponentiation
print(np.exp(a))  # [0.13533528 0.36787944 1.         2.71828183 7.3890561 ]


[0.13533528 0.36787944 1.         2.71828183 7.3890561 ]


In [9]:
# 07 - Natural logarithm
print(np.log(np.abs(a)))  # [0.69314718 0.69314718 -inf 0.         0.69314718]


[0.69314718 0.               -inf 0.         0.69314718]


C:\Users\HP ZBOOK 17\AppData\Local\Temp\ipykernel_11804\2753856065.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(np.abs(a)))  # [0.69314718 0.69314718 -inf 0.         0.69314718]


In [10]:
# 08 - Logarithm to base 10
print(np.log10(np.abs(a)))  # [0.30103    0.30103    -inf 0.         0.30103   ]


[0.30103 0.         -inf 0.      0.30103]


C:\Users\HP ZBOOK 17\AppData\Local\Temp\ipykernel_11804\2194247547.py:2: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(np.abs(a)))  # [0.30103    0.30103    -inf 0.         0.30103   ]


In [11]:
# 09 - Square root
print(np.sqrt(np.abs(a)))  # [1.41421356 1.         0.         1.         1.41421356]


[1.41421356 1.         0.         1.         1.41421356]


In [12]:
# 10 - Power
print(np.power(a, b))  # [-8 1 0 1 128]


[ -8   1   0   1 128]


In [13]:
# 11 - Maximum
print(np.maximum(a, b))  # [3 4 5 6 7]


[3 4 5 6 7]


In [14]:
# 12 - Minimum
print(np.minimum(a, b))  # [-2 -1 0 1 2]

[-2 -1  0  1  2]


In [15]:
# 13 - Modulo
print(np.mod(b, a))  # [1 3 5 0 2]

[-1  0  0  0  1]


C:\Users\HP ZBOOK 17\AppData\Local\Temp\ipykernel_11804\3291855529.py:2: RuntimeWarning: divide by zero encountered in remainder
  print(np.mod(b, a))  # [1 3 5 0 2]


In [16]:
# 14 - Ceiling
print(np.ceil(a))  # [-2 -1 0 1 2]

[-2. -1.  0.  1.  2.]


In [17]:
# 15 - Floor
print(np.floor(a))  # [-3 -2 -0 1 2]

[-2. -1.  0.  1.  2.]


In [18]:
# 16 - Cosine
print(np.cos(a))  # [ 0.41614684 -0.54030231  1.          0.54030231 -0.41614684]


[-0.41614684  0.54030231  1.          0.54030231 -0.41614684]


In [19]:
# 17 - Sine
print(np.sin(a))  # [0.90929743 0.84147098 0.         0.84147098 0.90929743]


[-0.90929743 -0.84147098  0.          0.84147098  0.90929743]


In [20]:
# 18 - Tangent
print(np.tan(a))  # [-2.18503986 -1.55740772 0.         1.55740772 2.18503986]


[ 2.18503986 -1.55740772  0.          1.55740772 -2.18503986]


In [21]:
# 19 - Inverse cosine
print(np.arccos(a/5))  # [2.67794505 2.14675497 1.57079633 1.14675497 0.67794505]


[1.98231317 1.77215425 1.57079633 1.36943841 1.15927948]


In [22]:
# 20 - Inverse sine
print(np.arcsin(a/5))  # [-1.36980409 -0.92729522 0.         0.92729522 1.36980409]


[-0.41151685 -0.20135792  0.          0.20135792  0.41151685]


# np.abs
# np.add
# np.subtract
# np.multiply
# np.divide
# np.exp
# np.log
# np.log10
# np.sqrt
# np.power
# np.maximum
# np.minimum
# np.mod
# np.ceil
# np.floor
# np.cos
# np.sin
# np.tan
# np.arccos
# np.arcsin